exclude: ^.*scapy/__version__\.py$|^.*setup.py
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
        name: Check for Blanket noqa
        exclude: tests
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Sorting imports
        exclude: tests
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        name: Formatting files
        exclude: tests
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Code quality check
        exclude: tests
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        name: Type checking
        additional_dependencies: [types-requests]
        exclude: tests
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        name: Security check
        exclude: tests
